//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MassConv
    {
        public long MassConvId { get; set; }
        public Nullable<long> MassId { get; set; }
        public Nullable<long> MassSubId { get; set; }
        public decimal Amt { get; set; }
    
        public virtual tblMassMaster tblMassMaster { get; set; }
        public virtual tblMassSub tblMassSub { get; set; }
    }
}
