//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDivision
    {
        public long DivId { get; set; }
        public string DivName { get; set; }
        public Nullable<int> BrId { get; set; }
        public Nullable<long> SchoolId { get; set; }
        public Nullable<long> StdId { get; set; }
    
        public virtual tblBranch tblBranch { get; set; }
        public virtual tblSchool tblSchool { get; set; }
        public virtual tblStd tblStd { get; set; }
    }
}
