//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGood
    {
        public long GoodsId { get; set; }
        public string Goods { get; set; }
        public decimal Qty { get; set; }
        public Nullable<long> MassSubId { get; set; }
        public Nullable<int> BrId { get; set; }
        public Nullable<long> SchoolId { get; set; }
        public Nullable<long> HostelId { get; set; }
    
        public virtual tblMassSub tblMassSub { get; set; }
        public virtual tblGood tblGoods1 { get; set; }
        public virtual tblGood tblGood1 { get; set; }
        public virtual tblHostel tblHostel { get; set; }
        public virtual tblSchool tblSchool { get; set; }
    }
}
