//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStudentParentDetail
    {
        public long StudentParentId { get; set; }
        public Nullable<long> ResumeId { get; set; }
        public string FatherFName { get; set; }
        public string FatherMName { get; set; }
        public string FatherLName { get; set; }
        public string FatherAdharNo { get; set; }
        public string FatherContactNo { get; set; }
        public string FatherEmail { get; set; }
        public string MotherFName { get; set; }
        public string MotherMName { get; set; }
        public string MotherrLName { get; set; }
        public string MotherAdharNo { get; set; }
        public string MotherContactNo { get; set; }
        public string MotherEmail { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string Pincode { get; set; }
        public Nullable<long> SchoolId { get; set; }
        public Nullable<int> BrId { get; set; }
    
        public virtual tblAdmission tblAdmission { get; set; }
        public virtual tblBranch tblBranch { get; set; }
        public virtual tblSchool tblSchool { get; set; }
    }
}
