//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehiclePrevillage
    {
        public System.Guid VehiclePrevillageId { get; set; }
        public Nullable<long> VehicleId { get; set; }
        public Nullable<long> VehicleTypeId { get; set; }
        public Nullable<int> BrId { get; set; }
        public Nullable<long> SchoolId { get; set; }
        public Nullable<long> ResumeId { get; set; }
    
        public virtual tblAdmission tblAdmission { get; set; }
        public virtual tblBranch tblBranch { get; set; }
        public virtual tblSchool tblSchool { get; set; }
        public virtual tblVehicle tblVehicle { get; set; }
        public virtual VechicleType VechicleType { get; set; }
    }
}
